# Generated by Django 3.2.4 on 2021-06-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expertise',
            field=models.CharField(blank=True, max_length=555),
        ),
        migrations.AddField(
            model_name='user',
            name='mentorship_areas',
            field=models.CharField(blank=True, max_length=555),
        ),
    ]
