# Generated by Django 3.2.4 on 2021-06-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20210630_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise', models.CharField(choices=[('UI/UX Design', 'UI/UX Design'), ('Product Design', 'Product Design'), ('AI Design', 'AI Design')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MentorshipAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentorship_areas', models.CharField(choices=[('Career Advice', 'Career Advice'), ('Portfolio Review', 'Portfolio Review'), ('Interview Techniques', 'Interview Techniques')], max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mentorship_areas',
        ),
        migrations.AddField(
            model_name='user',
            name='expertise',
            field=models.ManyToManyField(blank=True, related_name='expertise_rel', to='authentication.Expertise'),
        ),
        migrations.AddField(
            model_name='user',
            name='mentorship_areas',
            field=models.ManyToManyField(blank=True, related_name='mentorship_areas_rel', to='authentication.MentorshipAreas'),
        ),
    ]
