# Generated by Django 3.2.4 on 2021-06-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210630_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='expertise',
        ),
        migrations.AddField(
            model_name='user',
            name='expertise',
            field=models.CharField(blank=True, max_length=555),
        ),
        migrations.RemoveField(
            model_name='user',
            name='mentorship_areas',
        ),
        migrations.AddField(
            model_name='user',
            name='mentorship_areas',
            field=models.CharField(blank=True, max_length=555),
        ),
        migrations.DeleteModel(
            name='Expertise',
        ),
        migrations.DeleteModel(
            name='MentorshipAreas',
        ),
    ]
