# Generated by Django 3.2.4 on 2021-06-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210630_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expertise',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mentorship_areas',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
    ]
