# Generated by Django 3.2.4 on 2021-07-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20210701_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_mentor',
        ),
        migrations.AddField(
            model_name='user',
            name='joined_as',
            field=models.CharField(choices=[('mentor', 'mentor'), ('member', 'member')], default='member', max_length=10),
        ),
    ]
