# Generated by Django 3.2.4 on 2021-07-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnBoardingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_type', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('user_type', models.CharField(choices=[('mentor', 'mentor'), ('member', 'member')], max_length=20)),
            ],
            options={
                'ordering': ['user_type'],
            },
        ),
    ]
