# Generated by Django 3.2.4 on 2021-07-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingdata',
            name='content',
            field=models.CharField(max_length=555),
        ),
    ]
